name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: deploys the theme to production
    environment:
      name: production
      url: https://links.wien
    runs-on: ubuntu-latest
    steps:
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout
        uses: actions/checkout@v4

      - name: compile style.scss to style.css
        run: dart-sass scss/style.scss style.css --style compressed

      - name: ssh-keyscan for sftp
        run: |
          mkdir ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts

      - name: transfer files to server via sftp
        env: 
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: sshpass -e sftp ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} <<< 'put -R * /httpdocs/wp-content/themes/links-wien-theme'
